colors:
  # Default colors
  primary:
    background: "0xeeeeee"
    foreground: "0x2d2d2c"

  cursor:
    text: "0xf0f0f0"
    cursor: "0x1564bf"

  selection:
    text: "0xeaeaea"
    background: "0x00828e"

  # Normal colors
  normal:
    black: "0x2c2c2c"
    red: "0xc62727"
    green: "0x558b2e"
    yellow: "0xf9a824"
    blue: "0x1564bf"
    magenta: "0x691e99"
    cyan: "0x00828e"
    white: "0xcccccc"

  # Bright colors
  bright:
    black: "0x535353"
    red: "0xc62727"
    green: "0x558b2e"
    yellow: "0xf9a824"
    blue: "0x1564bf"
    magenta: "0x691e99"
    cyan: "0x00828e"
    white: "0xcccccc"

  # Dim colors
  #
  # If the dim colors are not set, they will be calculated automatically based
  # on the `normal` colors.
  # dim:
  #   black: "0x000000"
  #   red: "0x8c3336"
  #   green: "0x7a8530"
  #   yellow: "0x97822e"
  #   blue: "0x506d8f"
  #   magenta: "0x80638e"
  #   cyan: "0x497e7a"
  #   white: "0x9a9a9a"
# Background opacity
#
# Window opacity as a floating point number from `0.0` to `1.0`.
# The value `0.0` is completely transparent and `1.0` is opaque.
#background_opacity: 1.0
